[package]
name = "bubble-app"
version = "0.6.1"
edition = "2021"

[[bin]]
name = "bubble"
path = "src/main.rs"

[dependencies]
bubble-core = { path = "../bubble-core" }
dirs = "6.0.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
libc = "0.2.189"
qmetaobject = "0.2.10"
