[package]
name = "bubble-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

aes-gcm = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }

rusqlite = { workspace = true }

nix = { workspace = true }
xattr = { workspace = true }
walkdir = { workspace = true }
glob = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
url = { workspace = true }

thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
