[package]
name = "bubble-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "bubble_core"
crate-type = ["rlib", "staticlib"]

[dependencies]
libc = "0.2.189"
thiserror = "1.0.69"
dirs = "6.0.0"
serde = { version = "1.0.229", features = ["derive"] }
toml = "0.8.23"
regex = "1.13.1"
serde_json = "1.0.151"

[dev-dependencies]
tempfile = "3.27.0"
